In [1]:
import pandas as pd

In [2]:
import numpy as np

In [10]:
import matplotlib.pyplot as plt

In [11]:
from sklearn.linear_model import LinearRegression

In [12]:
df = pd.read_csv("homeprices.csv")

In [13]:
df

   area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [16]:
import math
median_bedrooms = math.floor(df.bedrooms.median())
median_bedrooms

4

In [18]:
df.bedrooms = df.bedrooms.fillna(median_bedrooms)

In [19]:
df

   area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [21]:
reg = LinearRegression()

In [22]:
reg

LinearRegression()

In [23]:
reg.fit(df[['area','bedrooms','age']], df.price)

LinearRegression()

In [24]:
reg.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [25]:
reg.intercept_

221323.0018654043

In [26]:
reg.predict([[3000,3,40]])

D:\Python\python\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([498408.25158031])

In [27]:
reg.predict([[3000,3,15]])

D:\Python\python\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([579201.19929613])

In [28]:
112.06244194 * 3000 + 23388.88007794*3 + -3231.71790863*15 + 221323.0018654043

579201.1992897743

In [29]:
reg.predict([[2500,4,5]])

D:\Python\python\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([578876.03748933])

In [30]:
df_exe = pd.read_csv('hiring.csv')

In [31]:
df_exe

  experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [32]:
from word2number import w2n

In [35]:
df_exe.experience = df_exe.experience.fillna("zero")

In [37]:
df_exe

  experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0       zero                    8.0                           9      50000
1       zero                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [38]:
df_exe.experience = df_exe.experience.apply(w2n.word_to_num)

In [39]:
df_exe

   experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    NaN                           7      72000
7          11                    7.0                           8      80000

In [40]:
import math
median_test_score = math.floor(df_exe['test_score(out of 10)'].mean())
median_test_score

7

In [41]:
df_exe['test_score(out of 10)'] = df_exe['test_score(out of 10)'].fillna(median_test_score)
df_exe

   experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    7.0                           7      72000
7          11                    7.0                           8      80000

In [44]:
reg = LinearRegression()
reg.fit(df_exe[['experience','test_score(out of 10)','interview_score(out of 10)']],df_exe['salary($)'])

LinearRegression()

In [45]:
reg.predict([[2,9,6]])

D:\Python\python\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([53713.86677124])

In [46]:
reg.predict([[12,10,10]])

D:\Python\python\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([93747.79628651])