In [1]:
import pandas as pd

In [2]:
india_weather = pd.DataFrame({
    "city": ["mumbai","delhi","banglore"],
    "temperature": [32,45,30],
    "humidity": [80, 60, 78]
})
india_weather

       city  temperature  humidity
0    mumbai           32        80
1     delhi           45        60
2  banglore           30        78

In [3]:
us_weather = pd.DataFrame({
    "city": ["new york","chicago","orlando"],
    "temperature": [21,14,35],
    "humidity": [68, 65, 75]
})
us_weather

       city  temperature  humidity
0  new york           21        68
1   chicago           14        65
2   orlando           35        75

In [4]:
df= pd.concat([india_weather,us_weather])

In [5]:
df

       city  temperature  humidity
0    mumbai           32        80
1     delhi           45        60
2  banglore           30        78
0  new york           21        68
1   chicago           14        65
2   orlando           35        75

In [6]:
df= pd.concat([india_weather,us_weather], ignore_index=True)

In [7]:
df

       city  temperature  humidity
0    mumbai           32        80
1     delhi           45        60
2  banglore           30        78
3  new york           21        68
4   chicago           14        65
5   orlando           35        75

In [10]:
df= pd.concat([india_weather,us_weather], keys = ["india","us"])

In [11]:
df

             city  temperature  humidity
india 0    mumbai           32        80
      1     delhi           45        60
      2  banglore           30        78
us    0  new york           21        68
      1   chicago           14        65
      2   orlando           35        75

In [12]:
df.loc["us"]

       city  temperature  humidity
0  new york           21        68
1   chicago           14        65
2   orlando           35        75

In [13]:
df.loc["india"]

       city  temperature  humidity
0    mumbai           32        80
1     delhi           45        60
2  banglore           30        78

In [14]:
temperature_df = pd.DataFrame({
    "city": ["mumbai","delhi","banglore"],
    "temperature": [32,45,30],
}, index=[0,1,2])
temperature_df

       city  temperature
0    mumbai           32
1     delhi           45
2  banglore           30

In [15]:
windspeed_df = pd.DataFrame({
    "city": ["delhi","mumbai"],
    "windspeed": [7,12],
}, index=[1,0])
windspeed_df

     city  windspeed
1   delhi          7
0  mumbai         12

In [16]:
df= pd.concat([temperature_df,windspeed_df], axis = 1)

In [17]:
df

       city  temperature    city  windspeed
0    mumbai           32  mumbai       12.0
1     delhi           45   delhi        7.0
2  banglore           30     NaN        NaN

In [18]:
#Concatenate dataframe with series

In [19]:
s = pd.Series(["Humid","Dry","Rain"], name = "event")
s

0    Humid
1      Dry
2     Rain
Name: event, dtype: object

In [20]:
df = pd.concat([temperature_df,s],axis=1)
df

       city  temperature  event
0    mumbai           32  Humid
1     delhi           45    Dry
2  banglore           30   Rain