In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("weather_data.csv")

In [3]:
df

         day  temperature  windspeed   event
0   1/1/2017         32.0        6.0    Rain
1   1/4/2017          NaN        9.0   Sunny
2   1/5/2017         28.0        NaN    Snow
3   1/6/2017          NaN        7.0     NaN
4   1/7/2017         32.0        NaN    Rain
5   1/8/2017          NaN        NaN   Sunny
6   1/9/2017          NaN        NaN     NaN
7  1/10/2017         34.0        8.0  Cloudy
8  1/11/2017         40.0       12.0   Sunny

In [4]:
type(df.day[0])

str

In [5]:
df = pd.read_csv("weather_data.csv", parse_dates=["day"])

In [6]:
type(df.day[0])

pandas._libs.tslibs.timestamps.Timestamp

In [7]:
new_df = df.fillna(0)

In [8]:
new_df

         day  temperature  windspeed   event
0 2017-01-01         32.0        6.0    Rain
1 2017-01-04          0.0        9.0   Sunny
2 2017-01-05         28.0        0.0    Snow
3 2017-01-06          0.0        7.0       0
4 2017-01-07         32.0        0.0    Rain
5 2017-01-08          0.0        0.0   Sunny
6 2017-01-09          0.0        0.0       0
7 2017-01-10         34.0        8.0  Cloudy
8 2017-01-11         40.0       12.0   Sunny

In [9]:
new_df = df.fillna({
    'temperature': 0,
    'windspeed': 0,
    'event' : 'no event'
})
new_df

         day  temperature  windspeed     event
0 2017-01-01         32.0        6.0      Rain
1 2017-01-04          0.0        9.0     Sunny
2 2017-01-05         28.0        0.0      Snow
3 2017-01-06          0.0        7.0  no event
4 2017-01-07         32.0        0.0      Rain
5 2017-01-08          0.0        0.0     Sunny
6 2017-01-09          0.0        0.0  no event
7 2017-01-10         34.0        8.0    Cloudy
8 2017-01-11         40.0       12.0     Sunny

In [10]:
new_df = df.fillna(method = "ffill")
new_df

C:\Users\aimga\AppData\Local\Temp\ipykernel_13076\3373491668.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  new_df = df.fillna(method = "ffill")

         day  temperature  windspeed   event
0 2017-01-01         32.0        6.0    Rain
1 2017-01-04         32.0        9.0   Sunny
2 2017-01-05         28.0        9.0    Snow
3 2017-01-06         28.0        7.0    Snow
4 2017-01-07         32.0        7.0    Rain
5 2017-01-08         32.0        7.0   Sunny
6 2017-01-09         32.0        7.0   Sunny
7 2017-01-10         34.0        8.0  Cloudy
8 2017-01-11         40.0       12.0   Sunny

In [11]:
new_df = df.fillna(method = "bfill")
new_df

C:\Users\aimga\AppData\Local\Temp\ipykernel_13076\1106947944.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  new_df = df.fillna(method = "bfill")

         day  temperature  windspeed   event
0 2017-01-01         32.0        6.0    Rain
1 2017-01-04         28.0        9.0   Sunny
2 2017-01-05         28.0        7.0    Snow
3 2017-01-06         32.0        7.0    Rain
4 2017-01-07         32.0        8.0    Rain
5 2017-01-08         34.0        8.0   Sunny
6 2017-01-09         34.0        8.0  Cloudy
7 2017-01-10         34.0        8.0  Cloudy
8 2017-01-11         40.0       12.0   Sunny

In [12]:
new_df = df.interpolate()

C:\Users\aimga\AppData\Local\Temp\ipykernel_13076\535524620.py:1: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  new_df = df.interpolate()

In [13]:
new_df

         day  temperature  windspeed   event
0 2017-01-01    32.000000       6.00    Rain
1 2017-01-04    30.000000       9.00   Sunny
2 2017-01-05    28.000000       8.00    Snow
3 2017-01-06    30.000000       7.00     NaN
4 2017-01-07    32.000000       7.25    Rain
5 2017-01-08    32.666667       7.50   Sunny
6 2017-01-09    33.333333       7.75     NaN
7 2017-01-10    34.000000       8.00  Cloudy
8 2017-01-11    40.000000      12.00   Sunny

In [14]:
df.set_index("day", inplace=True)

In [15]:
new_df = df.interpolate()

C:\Users\aimga\AppData\Local\Temp\ipykernel_13076\535524620.py:1: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  new_df = df.interpolate()

In [16]:
new_df

            temperature  windspeed   event
day
2017-01-01    32.000000       6.00    Rain
2017-01-04    30.000000       9.00   Sunny
2017-01-05    28.000000       8.00    Snow
2017-01-06    30.000000       7.00     NaN
2017-01-07    32.000000       7.25    Rain
2017-01-08    32.666667       7.50   Sunny
2017-01-09    33.333333       7.75     NaN
2017-01-10    34.000000       8.00  Cloudy
2017-01-11    40.000000      12.00   Sunny

In [17]:
new_df = df.interpolate(method = "time")

C:\Users\aimga\AppData\Local\Temp\ipykernel_13076\3411251304.py:1: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  new_df = df.interpolate(method = "time")

In [18]:
new_df

            temperature  windspeed   event
day
2017-01-01    32.000000       6.00    Rain
2017-01-04    29.000000       9.00   Sunny
2017-01-05    28.000000       8.00    Snow
2017-01-06    30.000000       7.00     NaN
2017-01-07    32.000000       7.25    Rain
2017-01-08    32.666667       7.50   Sunny
2017-01-09    33.333333       7.75     NaN
2017-01-10    34.000000       8.00  Cloudy
2017-01-11    40.000000      12.00   Sunny

In [19]:
new_df  = df.dropna()

In [20]:
new_df

            temperature  windspeed   event
day
2017-01-01         32.0        6.0    Rain
2017-01-10         34.0        8.0  Cloudy
2017-01-11         40.0       12.0   Sunny

In [21]:
new_df  = df.dropna(thresh = 1)

In [22]:
new_df

            temperature  windspeed   event
day
2017-01-01         32.0        6.0    Rain
2017-01-04          NaN        9.0   Sunny
2017-01-05         28.0        NaN    Snow
2017-01-06          NaN        7.0     NaN
2017-01-07         32.0        NaN    Rain
2017-01-08          NaN        NaN   Sunny
2017-01-10         34.0        8.0  Cloudy
2017-01-11         40.0       12.0   Sunny

In [23]:
new_df  = df.dropna(thresh = 2)

In [24]:
new_df

            temperature  windspeed   event
day
2017-01-01         32.0        6.0    Rain
2017-01-04          NaN        9.0   Sunny
2017-01-05         28.0        NaN    Snow
2017-01-07         32.0        NaN    Rain
2017-01-10         34.0        8.0  Cloudy
2017-01-11         40.0       12.0   Sunny