In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
df = pd.read_csv("weather.csv")

In [4]:
df

       date      city  temperature  humidity
0  5/1/2017  new york           65        56
1  5/2/2017  new york           66        58
2  5/3/2017  new york           68        60
3  5/1/2017    mumbai           75        80
4  5/2/2017    mumbai           78        83
5  5/3/2017    mumbai           82        85
6  5/1/2017   beijing           80        26
7  5/2/2017   beijing           77        30
8  5/3/2017   beijing           79        35

In [5]:
df.pivot(index="date", columns="city")

         temperature                 humidity
city         beijing mumbai new york  beijing mumbai new york
date
5/1/2017          80     75       65       26     80       56
5/2/2017          77     78       66       30     83       58
5/3/2017          79     82       68       35     85       60

In [6]:
df.pivot(index="date", columns="city" , values="humidity")

city      beijing  mumbai  new york
date
5/1/2017       26      80        56
5/2/2017       30      83        58
5/3/2017       35      85        60

In [7]:
##  pivot table (summerize and aggregate data inside dataframe)

In [8]:
df = pd.read_csv("weather2.csv")
df

       date      city  temperature  humidity
0  5/1/2017  new york           65        56
1  5/1/2017  new york           61        54
2  5/2/2017  new york           70        60
3  5/2/2017  new york           72        62
4  5/1/2017    mumbai           75        80
5  5/1/2017    mumbai           78        83
6  5/2/2017    mumbai           82        85
7  5/2/2017    mumbai           80        26

In [9]:
df.pivot_table(index="city",columns="date")

         humidity          temperature
date     5/1/2017 5/2/2017    5/1/2017 5/2/2017
city
mumbai       81.5     55.5        76.5     81.0
new york     55.0     61.0        63.0     71.0

In [10]:
# Margins

In [11]:
df.pivot_table(index="city",columns="date" , aggfunc=np.sum)

C:\Users\aimga\AppData\Local\Temp\ipykernel_14356\2580722873.py:1: FutureWarning: The provided callable <function sum at 0x000001EAE66454E0> is currently using DataFrameGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  df.pivot_table(index="city",columns="date" , aggfunc=np.sum)

         humidity          temperature
date     5/1/2017 5/2/2017    5/1/2017 5/2/2017
city
mumbai        163      111         153      162
new york      110      122         126      142

In [14]:
df.pivot_table(index="city",columns="date" , margins=True)

          humidity                                                            \
date     12/1/2017 12/2/2017 12/3/2017 5/1/2017 5/2/2017 5/3/2017        All
city
new york      50.0      52.0      51.0     56.0     54.0     60.0  53.833333
All           50.0      52.0      51.0     56.0     54.0     60.0  53.833333

         temperature
date       12/1/2017 12/2/2017 12/3/2017 5/1/2017 5/2/2017 5/3/2017   All
city
new york        30.0      28.0      25.0     65.0     61.0     70.0  46.5
All             30.0      28.0      25.0     65.0     61.0     70.0  46.5

In [15]:
# Grouper

In [16]:
df = pd.read_csv("weather3.csv")
df

        date      city  temperature  humidity
0   5/1/2017  new york           65        56
1   5/2/2017  new york           61        54
2   5/3/2017  new york           70        60
3  12/1/2017  new york           30        50
4  12/2/2017  new york           28        52
5  12/3/2017  new york           25        51

In [17]:
df['date'] = pd.to_datetime(df['date'])

In [18]:
df.pivot_table(index=pd.Grouper(freq='M',key='date'),columns='city')

C:\Users\aimga\AppData\Local\Temp\ipykernel_14356\3780491757.py:1: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  df.pivot_table(index=pd.Grouper(freq='M',key='date'),columns='city')

             humidity temperature
city         new york    new york
date
2017-05-31  56.666667   65.333333
2017-12-31  51.000000   27.666667