In [2]:
import pandas as pd
import sqlalchemy

In [ ]:
engine = sqlalchemy.create_engine('mysql+pymysql://root:[pass]@localhost:/application')

In [ ]:
df = pd.read_sql_table("customers",engine,columns=['name'])
df

In [ ]:
df = pd.read_sql_query("select id,name from customers",engine)
df

In [ ]:
query = '''
 SELECT customers.name, customers.phone_number, orders.name, orders.amount
 FROM customers INNER JOIN orders
 ON customers.id=orders.customer_id
'''
df = pd.read_sql_query(query,engine)
df

In [ ]:
query = '''
 SELECT customers.name, customers.phone_number, orders.name, orders.amount
 FROM customers INNER JOIN orders
 ON customers.id=orders.customer_id
'''
pd.read_sql(query,engine)

In [5]:
df = pd.read_csv("customers.csv")
df

     Customer Name  Customer Phone
0     rafael nadal      4567895647
1  maria sharapova       434534545
2   vladimir putin        89345345
3      kim un jong       123434456
4       jeff bezos       934534543
5     rahul gandhi        44324222

In [6]:
df.rename(columns={
    'Customer Name': 'name',
    'Customer Phone': 'phone_number'
}, inplace=True)
df

              name  phone_number
0     rafael nadal    4567895647
1  maria sharapova     434534545
2   vladimir putin      89345345
3      kim un jong     123434456
4       jeff bezos     934534543
5     rahul gandhi      44324222

In [ ]:
df.to_sql(
    name='customers', # database table name
    con=engine,
    if_exists='append',
    index=False
)