In [1]:
import pandas as pd

In [10]:
df = pd.read_csv("stock_data.csv", na_values = {
      'eps': ["not available","n.a."],
      'revenue':["not available","n.a.",-1],
      'price':["not available","n.a."],
      'people':["not available","n.a."]
})

In [11]:
df

  tickers    eps  revenue   price         people
0   GOOGL  27.82     87.0   845.0     larry page
1     WMT   4.61    484.0    65.0            NaN
2    MSFT  -1.00     85.0    64.0     bill gates
3    RIL     NaN     50.0  1023.0  mukesh ambani
4    TATA   5.60      NaN     NaN     ratan tata

In [13]:
df.to_csv('new.csv',index = False)

In [14]:
df.to_csv('new.csv',columns=['tickers','eps'],index = False)

In [15]:
##Excel

In [19]:
df = pd.read_excel('stock_data.xlsx','Sheet1')

In [20]:
df

  tickers            eps  revenue price         people
0   GOOGL          27.82       87   845     larry page
1     WMT           4.61      484    65           n.a.
2    MSFT             -1       85    64     bill gates
3    RIL   not available       50  1023  mukesh ambani
4    TATA            5.6       -1  n.a.     ratan tata

In [24]:
def convert_people_cell(cell):
    if cell == "n.a.":
        return 'sam walton'
    return cell

def convert_eps_cell(cell):
    if cell == "not available":
        return None
    return cell

In [25]:
df = pd.read_excel('stock_data.xlsx','Sheet1', converters = {
    'people' : convert_people_cell,
    'eps': convert_eps_cell,
})

In [26]:
df

  tickers    eps  revenue price         people
0   GOOGL  27.82       87   845     larry page
1     WMT   4.61      484    65     sam walton
2    MSFT  -1.00       85    64     bill gates
3    RIL     NaN       50  1023  mukesh ambani
4    TATA   5.60       -1  n.a.     ratan tata

In [29]:
df.to_excel("new.xlsx", sheet_name="stocks", startrow = 1, startcol = 2, index = False)