In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("weather.csv")

In [3]:
df

       date      city  temperature  humidity
0  5/1/2017  new york           65        56
1  5/2/2017  new york           66        58
2  5/3/2017  new york           68        60
3  5/1/2017    mumbai           75        80
4  5/2/2017    mumbai           78        83
5  5/3/2017    mumbai           82        85
6  5/1/2017   beijing           80        26
7  5/2/2017   beijing           77        30
8  5/3/2017   beijing           79        35

In [5]:
df1 = pd.melt(df,id_vars=["city"])
df1

        city     variable     value
0   new york         date  5/1/2017
1   new york         date  5/2/2017
2   new york         date  5/3/2017
3     mumbai         date  5/1/2017
4     mumbai         date  5/2/2017
5     mumbai         date  5/3/2017
6    beijing         date  5/1/2017
7    beijing         date  5/2/2017
8    beijing         date  5/3/2017
9   new york  temperature        65
10  new york  temperature        66
11  new york  temperature        68
12    mumbai  temperature        75
13    mumbai  temperature        78
14    mumbai  temperature        82
15   beijing  temperature        80
16   beijing  temperature        77
17   beijing  temperature        79
18  new york     humidity        56
19  new york     humidity        58
20  new york     humidity        60
21    mumbai     humidity        80
22    mumbai     humidity        83
23    mumbai     humidity        85
24   beijing     humidity        26
25   beijing     humidity        30
26   beijing     humidity        35

In [ ]:
melted = pd.melt(df, id_vars=["date"], var_name='city', value_name='temperature')
melted